//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.Subsequents = new HashSet<Subsequent>();
        }
    
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public string CertHolderFirstName { get; set; }
        public string CertHolderLastName { get; set; }
        public decimal LienAmount { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<bool> LookedUp { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public Nullable<System.DateTime> RedemptionDate { get; set; }
        public Nullable<int> CertificateType { get; set; }
        public Nullable<int> AccrualPeriod { get; set; }
        public Earning Earning { get; set; }
        public virtual CertificateType CertificateType1 { get; set; }
        public virtual Property Property { get; set; }
        public virtual ICollection<Subsequent> Subsequents { get; set; }
    }
}
