//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Earning
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int PropertyId { get; set; }
        public int EarningsTypeId { get; set; }
    
        public virtual EarningsType EarningsType { get; set; }
        public virtual Property Property { get; set; }
    }
}
