//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        public Municipality()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int Id { get; set; }
        public string MunicipalityName { get; set; }
        public int CountyId { get; set; }
        public bool LookUpRequirer { get; set; }
        public bool Calendar { get; set; }
        public bool Fiscal { get; set; }
    
        public virtual County County { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
