//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsequent
    {
        public int Id { get; set; }
        public decimal SubsequentAmount { get; set; }
        public decimal Above1500 { get; set; }
        public decimal Below1500 { get; set; }
        public System.DateTime OutLayDate { get; set; }
        public TimeSpan? AccrualPeriod { get; set; }
        public int CertificateId { get; set; }
        public int CertificateType { get; set; }
        public int PropertyId { get; set; }
        public Nullable<decimal> InterestEarnings { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual CertificateType CertificateType1 { get; set; }
        public virtual Property Property { get; set; }
    }
}
