//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxLienDataBaseEntities : DbContext
    {
        public TaxLienDataBaseEntities()
            : base("name=TaxLienDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CertificateType> CertificateTypes { get; set; }
        public DbSet<Earning> Earnings { get; set; }
        public DbSet<EarningsType> EarningsTypes { get; set; }
        public DbSet<Municipality> Municipalities { get; set; }
        public DbSet<Property> Properties { get; set; }
        public DbSet<PropertyType> PropertyTypes { get; set; }
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<Subsequent> Subsequents { get; set; }
        public DbSet<County> Counties { get; set; }
    }
}
